# Generated by Django 2.1 on 2019-08-23 10:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import socialize.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(default='socialize/profile_pic_empty.png', upload_to=socialize.models.cover_upload_path)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('about', models.TextField(null=True)),
                ('interest', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=250)),
                ('proj_link', models.CharField(blank=True, max_length=100)),
                ('proj_description', models.TextField()),
                ('proj_start_date', models.DateField()),
                ('proj_end_date', models.DateField(default=django.utils.timezone.now)),
                ('proj_status', models.BooleanField(default=False)),
                ('proj_GOC', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(to='socialize.Project'),
        ),
        migrations.CreateModel(
            name='myEmployee',
            fields=[
            ],
            options={
                'ordering': ['emp_id'],
                'proxy': True,
                'indexes': [],
            },
            bases=('socialize.employee', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
